### model
model_name_or_path: /home/yangzhe/Project/Eyjafjalla_chat/LlamaFactory/models/qwen2.5-7B-Instruct
quantization_bit: 4           # QLoRA: drastically reduces VRAM vs bf16 full weights
quantization_method: bnb      # choices: [bnb, hqq, eetq]
quantization_type: nf4        # choices: [nf4, fp4]
double_quantization: true
upcast_layernorm: true        # recommended for quantized training (more stable)
trust_remote_code: true

### method
stage: sft
do_train: true
finetuning_type: lora
lora_rank: 16
lora_dropout: 0.05
lora_target: all

### dataset
dataset: eyjafjalla_sft
template: qwen
cutoff_len: 2048
max_samples: null
preprocessing_num_workers: 16
dataloader_num_workers: 4

### output
output_dir: saves/qwen2.5-7b/lora/eyjafjalla_sft_v7
logging_steps: 10
save_steps: 500
plot_loss: true
overwrite_output_dir: true
save_only_model: false
report_to: none  # choices: [none, wandb, tensorboard, swanlab, mlflow]

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 8
learning_rate: 5.0e-5
num_train_epochs: 6.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
resume_from_checkpoint: null

### eval
# val_size: 0.1
# per_device_eval_batch_size: 1
# eval_strategy: steps
# eval_steps: 500
